export const NYX_GUIDE_STEPS = [
  {
    pose: 'welcome',
    kicker: 'Guia opcional',
    title: 'Quer um tour rápido?',
    lead: 'Eu te mostro o essencial do Ryxen abrindo as áreas reais do app, passo a passo.',
    note: 'Você pode sair a qualquer momento. O foco é te orientar sem atrapalhar.',
    chips: ['Hoje', 'Evolução', 'Conta'],
    targetLabel: 'Começo',
    targetText: 'Nyx vai te levando pela interface real do produto, sem cair em uma explicação genérica.',
  },
  {
    pose: 'present',
    kicker: 'Hoje',
    title: 'Aqui o dia já começa organizado.',
    lead: 'O app abre direto no treino do dia, com contexto claro e menos ruído para entrar no que importa.',
    note: 'O destaque agora aponta para o resumo principal do Hoje.',
    chips: ['Treino do dia', 'Semana ativa', 'Leitura rápida'],
    page: 'today',
    target: 'today-overview',
    targetLabel: 'Resumo do dia',
    targetText: 'Esse bloco concentra a sessão ativa, a origem do treino e a leitura mais rápida do que vem pela frente.',
  },
  {
    pose: 'present',
    kicker: 'Treino',
    title: 'Os blocos ficam no fluxo real de execução.',
    lead: 'Warm-up, força, metcon e acessórios aparecem no mesmo eixo, sem te empurrar para uma dashboard genérica.',
    note: 'Agora o destaque cai no conteúdo do treino carregado.',
    chips: ['Blocos reais', 'Execução', 'Menos desvio'],
    page: 'today',
    target: 'today-workout',
    targetLabel: 'Blocos do treino',
    targetText: 'É aqui que a sessão ganha corpo: linhas, intervalos, notas e ações práticas da rotina.',
  },
  {
    pose: 'curious',
    kicker: 'Importação',
    title: 'Quando quiser trocar a planilha, o caminho já está visível.',
    lead: 'A entrada de importação fica no próprio Hoje para PDF, imagem, vídeo, texto ou planilha.',
    note: 'O guia destaca o gatilho real do fluxo de importação sem tirar você do contexto.',
    chips: ['PDF', 'Imagem', 'Vídeo', 'Texto'],
    page: 'today',
    target: 'today-import',
    targetLabel: 'Atalho de importação',
    targetText: 'Esse botão abre o fluxo que importa ou troca o treino atual mantendo o restante do app no mesmo ritmo.',
  },
  {
    pose: 'present',
    kicker: 'Evolução',
    title: 'Seu progresso continua legível.',
    lead: 'Benchmarks, PRs e resultados recentes ficam em leitura direta, sem virar uma tela pesada.',
    note: 'O app abriu a área de evolução para você ver a estrutura real.',
    chips: ['Benchmarks', 'PRs', 'Histórico'],
    page: 'history',
    target: 'history-benchmarks',
    targetLabel: 'Benchmarks e tendência',
    targetText: 'A evolução aparece perto do uso real: menos ruído visual e mais continuidade na leitura.',
  },
  {
    pose: 'mentor',
    kicker: 'PRs',
    title: 'Seus records pessoais continuam perto do resto da evolução.',
    lead: 'A área de PRs fica no mesmo eixo do histórico para você registrar referência sem quebrar o fluxo.',
    note: 'O guia aponta a dobra real em que seus PRs vivem dentro do produto.',
    chips: ['PRs', 'Referências', 'Progressão'],
    page: 'history',
    target: 'history-prs',
    targetLabel: 'Seção de PRs',
    targetText: 'Aqui você mantém seus records pessoais e usa essas referências no dia a dia do treino.',
  },
  {
    pose: 'mentor',
    kicker: 'Conta',
    title: 'A visão geral junta acesso e atividade recente.',
    lead: 'Plano, acesso do atleta, portal do coach e sinais da conta ficam em uma leitura calma.',
    note: 'Agora o guia abriu a visão geral da conta.',
    chips: ['Acesso', 'Plano', 'Portal'],
    page: 'account',
    accountView: 'overview',
    target: 'account-access',
    targetLabel: 'Visão geral da conta',
    targetText: 'Essa parte concentra o essencial da conta antes de você entrar em preferências ou dados.',
  },
  {
    pose: 'mentor',
    kicker: 'Coach',
    title: 'O portal do coach fica separado, mas acessível no mesmo ecossistema.',
    lead: 'Se o plano liberar o portal, a entrada aparece na conta sem misturar gestão do box com o uso do atleta.',
    note: 'Nyx destaca a área real que mostra status do portal, renovação e caminho de entrada.',
    chips: ['Portal dedicado', 'Plano coach', 'Gestão separada'],
    page: 'account',
    accountView: 'overview',
    target: 'account-coach',
    targetLabel: 'Entrada do Coach Portal',
    targetText: 'Esse bloco concentra o status do portal e o acesso para a operação do box quando ela estiver ativa.',
  },
  {
    pose: 'present',
    kicker: 'Preferências',
    title: 'O visual e o treino ficam no seu ritmo.',
    lead: 'Densidade, tom de destaque, movimento e leitura do treino ficam juntos para ajustar o conforto do app.',
    note: 'O destaque foi para Preferências, já na superfície real da conta.',
    chips: ['Aparência', 'Densidade', 'Treino', 'Nyx'],
    page: 'account',
    accountView: 'preferences',
    target: 'account-preferences',
    targetLabel: 'Preferências reais',
    targetText: 'Você ajusta o app de verdade daqui, sem cair em uma janela isolada e sem perder o contexto.',
  },
  {
    pose: 'mentor',
    kicker: 'Dados',
    title: 'Seus backups e documentos ficam acessíveis.',
    lead: 'A parte de dados reúne backup, importação e o que está salvo neste aparelho em uma leitura mais prática.',
    note: 'Agora o guia levou você para Dados.',
    chips: ['Backup', 'Documentos', 'Migração'],
    page: 'account',
    accountView: 'data',
    target: 'account-data',
    targetLabel: 'Dados e backup',
    targetText: 'Essa área ajuda a cuidar do que foi salvo e do que pode ser levado para outro aparelho quando precisar.',
  },
  {
    pose: 'rest',
    kicker: 'Pronto',
    title: 'Agora você já sabe por onde começar.',
    lead: 'Nyx te acompanhou pelas áreas reais do produto. Quando quiser, o tour pode voltar.',
    note: 'O objetivo é clareza de produto, não excesso de tutorial.',
    chips: ['Tour opcional', 'Uso real', 'Sem ruído'],
    page: 'today',
    target: 'today-overview',
    targetLabel: 'Volta ao começo',
    targetText: 'Você já viu as superfícies centrais do app e pode seguir daí com bem menos atrito.',
  },
];

export function getNyxGuideStepCount() {
  return NYX_GUIDE_STEPS.length;
}

export function clampNyxGuideStep(step) {
  const index = Number(step);
  if (!Number.isInteger(index)) return 0;
  return Math.min(Math.max(index, 0), NYX_GUIDE_STEPS.length - 1);
}

export function getNyxGuideStep(step) {
  return NYX_GUIDE_STEPS[clampNyxGuideStep(step)] || NYX_GUIDE_STEPS[0];
}
